### ISSUE TITLE
TaskScheduler: 实现CreateTask

### ISSUE THREAD

**Issue by aquamarine5** [awesomehhhhh/Aesc.AwesomeKits#1]
Problems:
- [x] Trigger使用不明
_DotPeek:貌似有IWeeklyTrigger, etc.的接口可用，但需内部实现class_

**Comment by aquamarine5** [comment]
Step(4):
- 1.CreateTask()
- 2.**set** Trigger
- 3.**set** Action
- 4.SaveTask()

**Comment by awesomehhhhh** [comment]
Step(4):
- 1.CreateTask()
- 2. **set** Trigger
- 3. **set** Action
- 4.SaveTask()
